### PR TITLE
Abilty to correctly inform cargo of file dependnencies in build.rs

### PR DESCRIPTION
**Pull request by Carter12s**
## Description
See changelog.

## Fixes
Issue Number: None (just went for it)

## Checklist
- [x] Update CHANGELOG.md

### CODE REVIEW

**Review by ssnover — APPROVED** [review]
Looks good!

**Review by ssnover — CHANGES_REQUESTED** [review]
Actually, the test failure appears to be a real failure.

**Comment by Carter12s** [comment]
I believe test failure here is #141 and resolve by changes in #140 not going to address on this MR.

**Comment by Carter12s** [comment]
Going ahead and merging, will plan on fixing tests with continued work in #140

**Pull request merged**
